[project]
name = "nx-framework"
version = "0.0.3"
description = "Low-level FastAPI, asyncpg and Redis framework used by Nebula Broadcast and other projects."
authors = [
  {name = "Martin Wacker", email = "martas@imm.cz"},
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "aioshutil>=1.5",
    "asyncpg>=0.30.0",
    "fastapi>=0.115.8",
    "loguru>=0.7.3",
    "pydantic-settings>=2.7.1",
    "pydantic[email]>=2.10.6",
    "python-dotenv>=1.0.1",
    "redis>=5.2.1",
    "shortuuid>=1.0.13",
    "unidecode>=1.3.8",
]

[dependency-groups]
dev = [
    "asyncpg-stubs>=0.30.0",
    "mypy>=1.14.1",
    "ruff>=0.9.4",
    "types-aiofiles>=24.1.0.20241221",
]

[tool.ruff]
fix = true
line-length = 88

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = ["ALL"]

ignore = [
  "BLE",     # FIXME: blind exceptions. I don't like them either, but they are useful in some cases
  "COM812",  # OK: messes with formatter
  "D",       # FIXME: docstrings. Naaah.
  "EM",      # OK: String literals in exception messages (why not?)
  "FBT",     # Boolean positional argument (WTF?)
  "FIX002",  # FIXME: TODOs
  "ISC001",  # OK: Incompatible with formatting
  "PLR2004", # OK: Magic numbers (just a few)
  "PTH",     # FIXME: path-like objects
  "S101",    # OK: I like asserts. They make mypy happy
  "S104",    # OK: bind to all interfaces (We need this)
  "S110",    # OK: except: pass 
  "S608",    # FIXME: sql injections. let's wait for template strings
  "SIM105",  # OK: contextlib.suppress is ugly
  "TD002",   # Author name in TODOs
  "TD003",   # Issue link in TODOs
  "TRY003",  # OK: Avoid specicying long messages outside of exceptions
  "ANN",     # FIXME: Any
  "ERA",     # Commented out code
]

[tool.mypy]
plugins = [
  "pydantic.mypy"
]

check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_defs = true
exclude = "tests/|venv/|server/|api/"
explicit_package_bases = true
follow_imports = "silent"
no_implicit_reexport = true
strict = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
